import tick from '../Assets/Images/Akshay/Fill 4.png'
import cross from '../Assets/Icons/Vector (6).svg'

export const subitems = [
    {
        p :"Complimentary: 5 Free Days upon Sign-Up",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"Unlimited Post on Take the FLOOR",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"Unlimited Post on Take the MIC",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"Super User Badge",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"FAVORITES",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"CHAT OPTION",
        pic: tick,
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"ADMIRER/BE ADMIRED",
        // pic: tick,
        p1:"2/DAY",
        pic1:tick,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"AUDIO VOICE-NOTE MESSAGES",
        pic: cross,
        pic1:cross,
        pic2:tick,
        pic3:tick,
    },
    {
        p :"VIDEO",
        pic: cross,
        pic1:cross,
        pic2:cross,
        pic3:tick,
    },
    {
        p :"PICTURE UPLOAD",
        p1:"1PHOTO",
        p2:"3PHOTOS",
        p3:"4PHOTOS",
        p4:"5PHOTOS",
    },
    {
        p :"OPENING MATCHES",
        p1:"5MATCHES",
        p2:"10MATCHES",
        p3:"15MATCHES",
        p4:"20MATCHES",
    },
    {
        p :"NEW MATCHES UPDATE /DAY",
       p1:"1/DAY",
       p2:"3/DAY",
       p3:"4/DAY",
       p4:"5/DAY",
    },
    {
        p :"#ADMIRE /DAY",
       p1:"1/DAY",
       p2:"2/DAY",
       p3:"3/DAY",
       p4:"5/DAY",
    },
]