export const Page3Data = {
  status: [
    "Divorced",
    "Never Married",
    "Separated",
    "Single Parent",
    "Widowed",
  ],
  bodytypes: ["Big", "Chubby", "Plimp", "Slim", "Thin"],
  education: [
    "Bachelors of Arts",
    "Bachelors of Science",
    "HND",
    "JSCE",
    "MBA",
    "Masters",
    "OND",
    "Ph.D",
    "SSCE",
  ],
  height: ["Medium", "Short", "Tall"],

  employment: [
    "Accountant",
    "Activist",
    "Agriculturist (including Agronomist)",
    "Airport Traffic Controller",
    "Animal Breeser",
    "Animal Scientist",
    "Architect",
    "Auxiliary Nurse",
    "Baker",
    "Banker",
    "Branch Manager",
    "Business Owner",
    "Caterer",
    "Chemist",
    "Civil Servant",
    "claims Adjuster",
    "College Teacher",
    "Computer Systems Analyst",
    "Conservationalist",
    "Customer Services Representative",
    "Diary Scientist",
    "Dietitian",
    "Disaster Relief insurance",
    "Economist",
    "Entomologist",
    "Engineer",
    "Epidemiologist",
    "Evangelist",
    "Finance Controller",
    "Founder",
    "Forester",
    "Geneticist",
    "Geologist",
    "Geochemist",
    "Geophysicist",
    "Graphic Designer",
    "Horticulturist",
    "Interior Designer",
    "Land Surveyor",
    "Landscape Enforcement",
    "Law Enforcement",
    "Lawyer",
    "Lecturer",
    "Librarian",
    "Management Consultant",
    "marketer (other besides Banker)",
    "Mathematician (including Statistician Technologist",
    "Medical Laboratory Technologist",
    "Meteorologist",
    "Military",
    "Nutritionist",
    "Occupational Therapist",
    "Pastor",
    "Pharmacist",
    "Pharmacologist",
    "Physician",
    "Physiotherapist ? Physical Therapist",
    "Pilot",
    "Poultry Scientist",
    "Police Officer",
    "Radio Broadcaster",
    "Range Manager/Range",
    "Recreational Therapist",
    "Registered Nurse",
    "Research Assistant",
    "Scieentific Technician / Technologist",
    "Skilled Trade",
    "Social Media Manager",
    "Social Worker",
    "Software Develper",
    "Sylviculturist (including Forestry Specialist)",
    "Technical Publications Writer",
    "Urban Planner",
    "Veterinarian",
    "Vocational Counsellor",
    "Zoologist",
  ],
};

export const Page4Data = {
  religionlist: ["Agnostic","Christian","Muslim","Traditional worshipper","Other"],
  tribe: [
    "Aboriginals",
    "British",
    "Chewa",
    "Chinese",
    "Dinka",
    "French",
    "Fula",
    "Fulani",
    "Hausa",
    "Hutu",
    "Igbo",
    "Indian",
    "Indian",
    "Kanuri",
    "Kongo",
    "Luba",
    "Luo",
    "Malagasy",
    "Mande",
    "Massai",
    "Minority Tribe",
    "Mixed",
    "Mongo",
    "Moore",
    "Mossi",
    "Nama",
    "Nilotes",
    "Nuer",
    "Oromo",
    "Other",
    "San",
    "Sandawe",
    "Shona",
    "Somali",
    "Tigrayan",
    "White",
    "Yoruba",
    "Zulu",
  ],
};

export const Page5Data ={
  agerange : ['24-30','31-37','38-44','45-50','51-59','60-65'],
  lookingfor : ['A relationship that I can build on','A Serious Relationship','Marriage only seriously','Anywhere it goes','Just flirting']
}