export const Page3Data =
    {
        status : ["Single", "In a relationship", "Engaged", "Married", "Divorced", "Widowed", "It's complicated","Other"],
        bodytypes : [
            "Ectomorph",
            "Mesomorph",
            "Endomorph",
            "Hourglass",
            "Apple",
            "Pear",
            "Rectangle",
            "Inverted Triangle",
            "Diamond",
            "Oval",
            "Triangle",
            "Athletic",
            "Slender",
            "Curvy",
            "Petite",
            "Tall",
            "Short",
            "Average",
            "Chubby",
            "Muscular",
            "Other"
        ],
        education : [
            "High School",
            "Intermediate",
                "Associate's Degree",
                "Bachelor's Degree",
                "Master's Degree",
                "Doctorate (Ph.D.)",
                "Juris Doctor (J.D.)",
                "Doctor of Medicine (M.D.)",
                "Master of Business Administration (MBA)",
                "Master of Arts (M.A.)",
                "Master of Science (M.S.)",
                "Bachelor of Science in Nursing (B.S.N.)",
                "Other"
            ],
        employment : [   "Doctor",
        "Teacher",
        "Engineer",
        "Lawyer",
        "Accountant",
        "Architect",
        "Nurse",
        "Scientist",
        "Programmer",
        "Artist",
        "Musician",
        "Writer",
        "Chef",
        "Police officer",
        "Firefighter",
        "Dentist",
        "Pharmacist",
        "Veterinarian",
        "Pilot",
        "Athlete",
        "Psychologist",
        "Economist",
        "Journalist",
        "Electrician",
        "Plumber",
        "Carpenter",
        "Fashion designer",
        "Actor",
        "Photographer",
        "Librarian",
        'Other']
        }